**Worksheet-0**

**TO - DO - Task**

**4.1 Exercise on Functions:**

**Task - 1:**

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [1]:
def convert_units(value, from_unit, to_unit):
    conversions = {
        "m_to_ft": 3.28084,
        "ft_to_m": 1 / 3.28084,
        "kg_to_lbs": 2.20462,
        "lbs_to_kg": 1 / 2.20462,
        "L_to_gal": 0.264172,
        "gal_to_L": 1 / 0.264172
    }

    key = f"{from_unit}_to_{to_unit}"

    if key in conversions:
        return value * conversions[key]
    else:
        raise ValueError("Unsupported conversion")

def main():
    try:
        print("Select conversion type:")
        print("1. Length (m <-> ft)")
        print("2. Weight (kg <-> lbs)")
        print("3. Volume (L <-> gal)")

        choice = input("Enter 1, 2, or 3: ").strip()

        if choice == "1":
            from_unit = input("Convert from (m/ft): ").strip().lower()
            to_unit = "ft" if from_unit == "m" else "m"
        elif choice == "2":
            from_unit = input("Convert from (kg/lbs): ").strip().lower()
            to_unit = "lbs" if from_unit == "kg" else "kg"
        elif choice == "3":
            from_unit = input("Convert from (L/gal): ").strip().lower()
            to_unit = "gal" if from_unit == "L" else "L"
        else:
            print("Invalid choice!")
            return

        value = float(input("Enter the value to convert: "))
        result = convert_units(value, from_unit, to_unit)
        print(f"Converted value: {result:.4f} {to_unit}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception:
        print("An unexpected error occurred. Please try again.")

if __name__ == "__main__":
    main()


Select conversion type:
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)


Enter 1, 2, or 3:  2
Convert from (kg/lbs):  kg
Enter the value to convert:  50


Converted value: 110.2310 lbs


**Task - 2:**

Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
18
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

In [2]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The average of the numbers.
    """
    if not numbers:
        raise ValueError("Cannot calculate average of an empty list.")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Find the maximum number in a list.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The maximum number.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Find the minimum number in a list.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The minimum number.
    """
    return min(numbers)

def main():
    try:
        print("Select an operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = input("Enter 1, 2, 3, or 4: ").strip()
        operation_map = {"1": calculate_sum, "2": calculate_average, "3": find_maximum, "4": find_minimum}

        if choice not in operation_map:
            print("Invalid choice!")
            return

        numbers_input = input("Enter a list of numbers separated by spaces: ").strip()
        numbers = [float(num) for num in numbers_input.split()]

        if not numbers:
            print("Error: No numbers entered.")
            return

        result = operation_map[choice](numbers)
        print(f"Result: {result:.4f}")

    except ValueError as e:
        print(f"Error: {e}")
    except Exception:
        print("An unexpected error occurred. Please try again.")

if __name__ == "__main__":
    main()


Select an operation:
1. Sum
2. Average
3. Maximum
4. Minimum


Enter 1, 2, 3, or 4:  2
Enter a list of numbers separated by spaces:  5 6 8 7 9 10


Result: 7.5000


**4.2 Exercise on List Manipulation:**


**1. Extract Every Other Element:**

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [3]:
def extract_every_other(lst):

    return lst[::2]

lst = [1, 2, 3, 4, 5, 6]
print("Every other element:", extract_every_other(lst))


Every other element: [1, 3, 5]


**2. Slice a Sublist:**

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].


In [4]:

def get_sublist(lst, start, end):
    return lst[start:end+1]

# Example usage:
print("Sublist (2 to 4):", get_sublist(lst, 2, 4))



Sublist (2 to 4): [3, 4, 5]


**3. Reverse a List Using Slicing:**

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [5]:
def reverse_list(lst):

    return lst[::-1]

# Example usage:
print("Reversed list:", reverse_list(lst))

Reversed list: [6, 5, 4, 3, 2, 1]


**4. Remove the First and Last Elements:**

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4]

In [6]:

def remove_first_last(lst):

    return lst[1:-1]

# Example usage:
print("Removed first and last:", remove_first_last(lst))

Removed first and last: [2, 3, 4, 5]


**5. Get the First n Elements:**

Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].


In [7]:

def get_first_n(lst, n):

    return lst[:n]

# Example usage:
print("First 3 elements:", get_first_n(lst, 3))


First 3 elements: [1, 2, 3]


**6. Extract Elements from the End:**

Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [8]:
def get_last_n(lst, n):
    return lst[-n:]

lst = [1, 2, 3, 4, 5]
n = 2
print(get_last_n(lst, n))  


[4, 5]


**7. Extract Elements in Reverse Order:**

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [9]:
def reverse_skip(lst):
    return lst[-2::-2]

# Example usage:
lst = [1, 2, 3, 4, 5, 6]
print(reverse_skip(lst))  


[5, 3, 1]


**4.3 Exercise on Nested List:**


**1. Flatten a Nested List:**

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [10]:
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))  
        else:
            result.append(item)
    return result

print(flatten([[1, 2], [3, 4], [5]]))  

[1, 2, 3, 4, 5]


**2. Accessing Nested List Elements:**

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [11]:
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]
    return lst

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
print(access_nested_element(lst, indices))  


6


**3. Sum of All Elements in a Nested List:**

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21

In [12]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

print(sum_nested([[1, 2], [3, [4, 5]], 6]))  

21


**4. Remove Specific Element from a Nested List:**

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [13]:
def remove_element(lst, elem):
    if isinstance(lst, list):
        return [remove_element(item, elem) for item in lst if item != elem]
    return lst

lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
print(remove_element(lst, elem))  

[[1], [3], [4, 5]]


**5. Find the Maximum Element in a Nested List:**

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [14]:
def find_max(lst):
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

print(find_max([[1, 2], [3, [4, 5]], 6]))  

6


**6. Count Occurrences of an Element in a Nested List:**
Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [15]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
print(count_occurrences(lst, elem))  

3


**7. Flatten a List of Lists of Lists:**

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8]

In [16]:
def deep_flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  

[1, 2, 3, 4, 5, 6, 7, 8]


**8. Nested List Average:**

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.


In [17]:
def average_nested(lst):
    total, count = 0, 0
    def helper(lst):
        nonlocal total, count
        for item in lst:
            if isinstance(item, list):
                helper(item)
            else:
                total += item
                count += 1
    helper(lst)
    return total / count if count > 0 else 0

print(average_nested([[1, 2], [3, 4], [5, 6]]))  

3.5


**10 To - Do - NumPy**

**10.1 Basic Vector and Matrix Operation with Numpy.**

Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [18]:
import numpy as np

array1 = np.empty((2, 2))
print("Empty array (2x2):\n", array1)

array2 = np.ones((4, 2))
print("\nAll-one array (4x2):\n", array2)

array3 = np.full((3, 3), 7)
print("\nArray filled with 7 (3x3):\n", array3)

array4 = np.zeros_like(array2)
print("\nZeros array with same shape as array2:\n", array4)

array5 = np.ones_like(array2)
print("\nOnes array with same shape as array2:\n", array5)

new_list = [1, 2, 3, 4]
array6 = np.array(new_list)
print("\nConverted list to array:", array6)


Empty array (2x2):
 [[8.38411072e+169 3.21431190e-057]
 [6.56329461e-091 4.85560391e-033]]

All-one array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros array with same shape as array2:
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Ones array with same shape as array2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Converted list to array: [1 2 3 4]


**Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [19]:
array7 = np.arange(10, 50)
print("\nArray from 10 to 49:\n", array7)

array8 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix from 0 to 8:\n", array8)

identity_matrix = np.eye(3)
print("\nIdentity matrix (3x3):\n", identity_matrix)

random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array mean:", mean_value)

random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\nMin value:", min_value, "Max value:", max_value)

array9 = np.zeros(10)
array9[4] = 1
print("\nZero array with 5th element replaced by 1:\n", array9)

arr = [1, 2, 0, 0, 4, 0]
reversed_arr = np.flip(arr)
print("\nReversed array:", reversed_arr)

array10 = np.ones((5, 5))
array10[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", array10)

checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard pattern (8x8):\n", checkerboard)



Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array mean: 0.433229416110641

Min value: 0.022380432173579545 Max value: 0.9993133928524945

Zero array with 5th element replaced by 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array: [0 4 0 0 2 1]

2D array with 1 on border and 0 inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard pattern (8x8):
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


**Problem - 3: Array Operations:**

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [20]:
# Arrays for operations
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_result = x + y
print("\nAddition of x and y:\n", add_result)

subtract_result = x - y
print("\nSubtraction of x and y:\n", subtract_result)

multiply_result = x * 2
print("\nMultiplication of x by 2:\n", multiply_result)

square_result = np.square(x)
print("\nSquare of each element in x:\n", square_result)

dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product v . w:", dot_vw)
print("Dot product x . v:\n", dot_xv)
print("Dot product x . y:\n", dot_xy)

concat_xy_row = np.concatenate((x, y), axis=1)
print("\nConcatenation of x and y along row:\n", concat_xy_row)

concat_vw_col = np.vstack((v, w))
print("\nConcatenation of v and w along column:\n", concat_vw_col)

try:
    concat_xv = np.concatenate((x, v), axis=1)
except Exception as e:
    print("\nError during concatenation of x and v:", e)



Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

Square of each element in x:
 [[ 1  4]
 [ 9 25]]

Dot product v . w: 219
Dot product x . v:
 [29 77]
Dot product x . y:
 [[19 22]
 [50 58]]

Concatenation of x and y along row:
 [[1 2 5 6]
 [3 5 7 8]]

Concatenation of v and w along column:
 [[ 9 10]
 [11 12]]

Error during concatenation of x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem - 4: Matrix Operations:**

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)
T = BTAT


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}

In [21]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("\nA * A^-1 (should be identity matrix):\n", identity_matrix)

#AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)

# (AB)^T = B^T * A^T
AB_transpose = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\nTranspose of AB:\n", AB_transpose)
print("B^T * A^T:\n", BT_AT)

#linear equations
coeff_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
const_matrix = np.array([-1, -3, 9])


solution = np.linalg.solve(coeff_matrix, const_matrix)
print("\nSoln to the system of equations (x, y, z):", solution)



A * A^-1 (should be identity matrix):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]

Transpose of AB:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]

Soln to the system of equations (x, y, z): [ 2.  1. -2.]


**10.2 Experiment: How Fast is Numpy?**


**1. Element-wise Addition:**

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [22]:
import time

list1 = [i for i in range(1000000)]
list2 = [i for i in range(1000000)]

start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(1000000)]
end_time = time.time()

print(f"Time taken for element-wise addition using Python lists: {end_time - start_time} seconds")


Time taken for element-wise addition using Python lists: 0.08632183074951172 seconds


**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measur
e and print the time taken for
this operation.


In [23]:
import numpy as np

arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start_time = time.time()
result_arr = arr1 + arr2
end_time = time.time()

print(f"Time taken for element-wise addition using NumPy arrays: {end_time - start_time} seconds")


Time taken for element-wise addition using NumPy arrays: 0.005480527877807617 seconds


**2. Element-wise Multiplication**

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [24]:
start_time = time.time()
result_mult_list = [list1[i] * list2[i] for i in range(1000000)]
end_time = time.time()

print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time} seconds")


Time taken for element-wise multiplication using Python lists: 0.10989642143249512 seconds


In [25]:
start_time = time.time()
result_mult_arr = arr1 * arr2
end_time = time.time()

print(f"Time taken for element-wise multiplication using NumPy arrays: {end_time - start_time} seconds")


Time taken for element-wise multiplication using NumPy arrays: 0.0062770843505859375 seconds


**3. Dot Product**

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.


In [26]:
start_time = time.time()
dot_product_list = sum([list1[i] * list2[i] for i in range(1000000)])
end_time = time.time()

print(f"Time taken for dot product using Python lists: {end_time - start_time} seconds")


Time taken for dot product using Python lists: 0.1382749080657959 seconds


In [32]:
start_time = time.time()
dot_product_arr = np.dot(arr1, arr2)
end_time = time.time()

print(f"Time taken for dot product using NumPy arrays: {end_time - start_time} seconds")


Time taken for dot product using NumPy arrays: 0.0027551651000976562 seconds


**4. Matrix Multiplication**

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [33]:
matrix1 = [[i + j for j in range(1000)] for i in range(1000)]
matrix2 = [[i - j for j in range(1000)] for i in range(1000)]

start_time = time.time()
result_matrix_list = [
    [sum(matrix1[i][k] * matrix2[k][j] for k in range(1000)) for j in range(1000)] 
    for i in range(1000)
]
end_time = time.time()

print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time} seconds")


Time taken for matrix multiplication using Python lists: 93.45408892631531 seconds


In [29]:
matrix1_arr = np.random.rand(1000, 1000)
matrix2_arr = np.random.rand(1000, 1000)

start_time = time.time()
result_matrix_arr = np.dot(matrix1_arr, matrix2_arr)
end_time = time.time()

print(f"Time taken for matrix multiplication using NumPy arrays: {end_time - start_time} seconds")


Time taken for matrix multiplication using NumPy arrays: 0.017350435256958008 seconds
